/* AUTO-GENERATED by sync-engine generator. Do not edit. */
import { getEnv } from "@/utils/env";

const TABLE = __TABLE__;

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function err(message: string, status = 400) {
  return json({ error: message }, status);
}

__CHECK_TYPE__

function validate(obj: Record<string, unknown>): { ok: boolean; error?: string } {
  const keys = Object.keys(obj);
  if (keys.length === 0) return { ok: false, error: "No fields provided" };

  const allowed: Record<string, string | string[] | null> = __ALLOWED_LITERAL__;

  for (const k of keys) {
    if (!Object.prototype.hasOwnProperty.call(allowed, k)) return { ok: false, error: `Unexpected field for ${TABLE}: ${k}` };
    // nested object and enum checks
    __CUSTOM_CHECKS__
    if (!checkType(obj[k], allowed[k] as any)) return { ok: false, error: `Invalid type for ${k}` };
  }
  return { ok: true };
}

function validatePartial(obj: Record<string, unknown>): { ok: boolean; error?: string } {
  const keys = Object.keys(obj).filter((k) => k !== "id");
  if (keys.length === 0) return { ok: false, error: "No fields to update" };

  const allowed: Record<string, string | string[] | null> = __ALLOWED_LITERAL__;

  for (const k of keys) {
    if (!Object.prototype.hasOwnProperty.call(allowed, k)) return { ok: false, error: `Unexpected field for ${TABLE}: ${k}` };
    __CUSTOM_CHECKS__
    if (!checkType(obj[k], allowed[k] as any)) return { ok: false, error: `Invalid type for ${k}` };
  }
  return { ok: true };
}

export async function GET(request: Request) {
  const env = getEnv();
  const url = new URL(request.url);
  const selectParam = url.searchParams.get("select") || "";
  const selectFields = selectParam.split(",").map((s) => s.trim()).filter(Boolean);
  const columns = selectFields.length ? selectFields.join(", ") : "*";

  const where: string[] = [];
  const bindings: unknown[] = [];
  for (const [key, value] of url.searchParams) {
    if (key === "select") continue;
    if (value === "null") {
      where.push(`${key} IS NULL`);
    } else {
      where.push(`${key} = ?`);
      bindings.push(value);
    }
  }

  const sql = `SELECT ${columns} FROM ${TABLE}` + (where.length ? ` WHERE ${where.join(" AND ")}` : "");
  const { results } = await env.DB.prepare(sql).bind(...bindings).all();
  return json(results || []);
}

export async function POST(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { data: Record<string, unknown>; client_id: string; client_op_id: string } | null;
  const data = body?.data;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;
  if (!data || typeof data !== "object") return err("Invalid JSON body, expected { data: { ... } }");
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");

  const v = validate(data as Record<string, unknown>);
  if (!v.ok) return err(v.error ?? "Validation error");

  const { results: tableInfo } = await env.DB.prepare(`PRAGMA table_info(${TABLE})`).all();
  const existingCols = new Set<string>((tableInfo || []).map((r: any) => r.name));
  const allColumns = Object.keys(data as Record<string, unknown>);
  const columns = allColumns.filter((c) => existingCols.has(c));
  const missingColumns = allColumns.filter((c) => !existingCols.has(c));
  if (missingColumns.length) {
    console.warn(`Inserting into ${TABLE}: skipping unknown columns: ${missingColumns.join(", ")}`);
  }
  if (columns.some((c) => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(c))) return err("Invalid field name");

  const placeholders = columns.map(() => "?").join(", ");
  const sql = `INSERT INTO ${TABLE} (${columns.join(", ")}) VALUES (${placeholders})`;
  const bindings = columns.map((c) => {
    const v = (data as any)[c];
    return v !== null && typeof v === "object" ? JSON.stringify(v) : v;
  });

  if (columns.length === 0) return err("No valid columns to insert for table", 400);

  const stmts = [env.DB.prepare(sql).bind(...bindings)];
  const payloadInsert = JSON.stringify({ action: "insert", data });
  const { results: opsInfo } = await env.DB.prepare(`PRAGMA table_info(operations)`).all();
  const opsIdCol = (opsInfo || []).find((r: any) => r.name === "id");
  const opIdValue = opsIdCol && String(opsIdCol.type || "").toUpperCase() === "INTEGER" && Number(opsIdCol.pk) === 1 ? null : crypto.randomUUID();

  stmts.push(env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'insert', ?, ?, ?, ?, 0, ?)`)
    .bind(opIdValue, TABLE, payloadInsert, client_id ?? null, client_op_id ?? null, Date.now(), (data as any).id !== undefined ? String((data as any).id) : null));

  try {
    await env.DB.batch(stmts);
  } catch (e) {
    console.error('DB batch error:', e);
    return err(String(e), 500);
  }

  let result = null;
  if ((data as any).id !== undefined) {
    result = await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).bind((data as any).id).first();
  } else {
    result = (await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE rowid = last_insert_rowid()`).first()) || null;
  }

  return json(result || {}, 201);
}

export async function PUT(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { data?: Record<string, unknown>; client_id?: string; client_op_id?: string } | null;
  const data = body?.data;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;
  if (!data || typeof data !== "object") return err("Invalid JSON body, expected { data: { ... } }");
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");

  const id = (data as any).id;
  if (id === undefined || (typeof id !== "string" && typeof id !== "number")) return err("Missing or invalid id in data");

  const v = validatePartial(data as Record<string, unknown>);
  if (!v.ok) return err(v.error ?? "Validation error");

  const updates = Object.keys(data as Record<string, unknown>).filter((k) => k !== "id");
  if (updates.some((c) => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(c))) return err("Invalid field name");

  const setClauses = updates.map((c) => `${c} = ?`);
  const bindings = updates.map((c) => {
    const v = (data as any)[c];
    if (v === null) return null;
    if (typeof v === "object") return JSON.stringify(v);
    return v;
  });
  setClauses.push("updated_at = strftime('%s', 'now')");

  const sql = `UPDATE ${TABLE} SET ${setClauses.join(", ")} WHERE id = ?`;
  bindings.push(id as unknown);

  const stmtsUpd = [env.DB.prepare(sql).bind(...bindings)];
  const payloadUpdate = JSON.stringify({ action: "update", id, changes: updates.reduce((acc: Record<string, unknown>, k) => { acc[k] = (data as any)[k]; return acc; }, {}) });

  const lastOp = await env.DB.prepare(`SELECT id, payload FROM operations WHERE entity = ? AND instance_id = ? AND client_id = ? AND op_type = 'update' ORDER BY created_at DESC, id DESC LIMIT 1`) 
    .bind(TABLE, String(id), client_id)
    .first();

  let compactSuccess = false;
  if (lastOp && lastOp.payload) {
    try {
      const oldPayload = JSON.parse(lastOp.payload);
      const newPayload = JSON.parse(payloadUpdate);
      const mergedChanges = { ...oldPayload.changes, ...newPayload.changes };
      const mergedPayload = JSON.stringify({ ...oldPayload, changes: mergedChanges });

      stmtsUpd.push(env.DB.prepare(`UPDATE operations SET payload = ?, created_at = ? WHERE id = ?`).bind(mergedPayload, Date.now(), lastOp.id));
      compactSuccess = true;
    } catch (e) {
      console.warn("Failed to compact operation", e);
    }
  }

  if (!compactSuccess) {
    const { results: opsInfoUpd } = await env.DB.prepare(`PRAGMA table_info(operations)`).all();
    const opsIdColUpd = (opsInfoUpd || []).find((r: any) => r.name === "id");
    const opIdValueUpd = opsIdColUpd && String(opsIdColUpd.type || "").toUpperCase() === "INTEGER" && Number(opsIdColUpd.pk) === 1 ? null : crypto.randomUUID();

    stmtsUpd.push(env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'update', ?, ?, ?, ?, 0, ?)`).bind(opIdValueUpd, TABLE, payloadUpdate, client_id ?? null, client_op_id ?? null, Date.now(), String(id)));
  }

  await env.DB.batch(stmtsUpd);

  const result = await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).bind(id).first();
  return json(result || {});
}

export async function DELETE(request: Request) {
  const env = getEnv();
  const body = (await request.json().catch(() => null)) as { id?: unknown; client_id?: string; client_op_id?: string } | null;
  let id = body?.id;
  const client_id = body?.client_id;
  const client_op_id = body?.client_op_id;
  if (!client_id || !client_op_id) return err("Missing client_id or client_op_id");

  if (id === undefined) {
    const url = new URL(request.url);
    const idParam = url.searchParams.get("id");
    if (idParam !== null) id = Number(idParam);
  }

  if (id === undefined || id === null) return err("Missing or invalid id");

  const stmtsDel = [env.DB.prepare(`DELETE FROM ${TABLE} WHERE id = ?`).bind(id)];
  const payloadDelete = JSON.stringify({ action: "delete", id });
  const { results: opsInfoDel } = await env.DB.prepare(`PRAGMA table_info(operations)`).all();
  const opsIdColDel = (opsInfoDel || []).find((r: any) => r.name === "id");
  const opIdValueDel = opsIdColDel && String(opsIdColDel.type || "").toUpperCase() === "INTEGER" && Number(opsIdColDel.pk) === 1 ? null : crypto.randomUUID();
  stmtsDel.push(env.DB.prepare(`INSERT INTO operations (id, entity, op_type, payload, client_id, client_op_id, created_at, undone, instance_id) VALUES (?, ?, 'delete', ?, ?, ?, ?, 0, ?)`).bind(opIdValueDel, TABLE, payloadDelete, client_id ?? null, client_op_id ?? null, Date.now(), String(id)));
  await env.DB.batch(stmtsDel);

  return json({ success: true });
}
